### PR TITLE
Pre release updates

### PR DESCRIPTION
**Pull request by legoboyvdlp**

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
I really wish you had left this repo alone, with _**my**_ repo as the sole place to push to. Now I have to go running about doing pull requests every day, when someone pushes a livery or something.

Nice liveries, but still....

**Comment by aiannuzzi99** [comment]
Yeah sorry about that but I still have like 4 or 5 liveries that people
requested that I make for that aircraft.

-ACI

**Comment by legoboyvdlp** [comment]
If you like, I'll give you push access to my repo, and then you can push directly :)
No need to reclone, simply change your remotes.

At you on risk, edit the CONFIG file to the new remote URL. This file is inside your 787-9/.git/ folder.
At your own risk.

In this case, replace the word FGMEMBERS inside the url to the origin with 'legoboyvdlp '(no caps)

Or else,  reclone, or else, change remotes via command line

https://www.google.co.ve/search?q=how+to%3Achange+github+remotes&oq=how+to%3Achange+github+remotes&aqs=chrome..69i57.5134j0j4&client=tablet-android-samsung&sourceid=chrome-mobile&ie=UTF-8

**Comment by aiannuzzi99** [comment]
Yah I am not experienced with any lines of code or any programming the only
things

**Comment by aiannuzzi99** [comment]
That I can do is the livery cal file if someone can come on mumble and help
me then maybe I can do all of that stuff.

**Comment by ghost** [comment]
Simply copy your 787-9 to.. let's say 787-10, just for secure. Then go 
into the 787-9 folder, into ".git" and change your CONFIG file as lego 
said.
That should imo be more or less riskless

Am 11.02.2016 um 15:21 schrieb aiannuzzi99:

> That I can do is the livery cal file if someone can come on mumble and 
> help
> me then maybe I can do all of that stuff.
> 
> On Thursday, February 11, 2016, Alex Iannuzzi <

**Comment by FGDATA** [comment]
> I really wish you had left this repo alone, with my repo as the sole place to push to. Now I have to go running about doing pull requests every day, when someone pushes a livery or something.

So, exactly why is Lego bullying AIC now?

Lego, **AIC HAS push permissions to the FGMEMBERS repository,** and if he feels comfortable pushing in the 787-9 fork of FGMEMBERS, he is doing rightly so. 
You can give him push permission to the dev repo as well, but in any case, AIC can still freely decide where and how to push.  [As a matter of fact, he could fork and push to his fork and send PR to anywhere as well._ That is the principle of a distributed development infrastructure_] 
Ultimately, for you to bring a commit from one fork into another is the simplest of all tasks. Way much easier than commiting. And if in doubt, I can instruct you how is don

**Comment by FGDATA** [comment]
> At you on risk, edit the CONFIG file to the new remote URL. This file is inside your 787-9/.git/ folder.
> At your own risk.

**That is a terribly bad way of doing it. Why risk it?**

Reading: http://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes

```
  git remote add <alias> <url>
```

Allows you to have several remotes properly configured in your git 

example

```
       git remote add development git@github.com:FGMEMBERS/787-9.git
```

Will then allow you to do things like

```
    git pull development master
```

or 

```
    git push development master
    git push origin master
```

**Comment by aiannuzzi99** [comment]
Are u able to come on mumble and explain all of this for me tomorrow
because I don't use code and I don't really know what you and legoboy are
talking about lol.

**Comment by IAHM-COL** [comment]
Not able to. But as a summary, dont worry
1. Push to FGMEMBERS. Feel confident doing so. you are Fully authorized.
2. Lego can very easily implement the liveries / or any other change / in
   his repo. So you dont' have to worry much about it
3. Lego can give you push access to his repository. This way you could push
   to the repo he hosted instead (or as well). At the end of the day, there is no
   difference.

**Comment by aiannuzzi99** [comment]
Ok, so I got push access to his repository, do I still have to push it to
the FGMEMBERS repository also?

ACI

**Comment by FGDATA** [comment]
"Have to" is a very strongly worded way.
You could. If you wish so. But it is very simple to push to different repositories if they are forks of each others. 

Basically if he gives you push access to his repository your posibilities increase
1. you can push to his repo (the dev repo)
2. you can push to FGMEMBERS 
3. you can do both.

neither of these is harder than other.

they way lego mentioned above is bad idea. The easy way is

In your repo in git :

```
          git remote add development git@github.com:legoboyvdlp/787-9.git
```

That adds a  remote, named development that reffers to Lego's
origin means FGMEMBERS, since you cloned from it

so

```
      git pull origin master 
```

updates your repo to new stuff in FGMEMBERS

```
       git pull development master
```

updates your repo to new stuff in Lego's

```
       git push origin master
```

Update the FGMEMBERS repo (you can since you have push access to FGMEMBERS)

```
       git push development master
```

Update lego's repo (you could if lego grants you access)

In principle, do not manually edit the config file of git.

**Pull request merged**
